
import type { Metadata } from "next";
import { Libre_Franklin } from 'next/font/google'
import "./globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "@/components/theme-provider";
const libre_franklin = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre_franklin',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <ThemeProvider
       attribute="class"
       defaultTheme="system"
       enableSystem
       disableTransitionOnChange>
      <body className={libre_franklin.className}>
        <Header />
        {children}</body>
        </ThemeProvider>
    </html>
  );
}
